version: '3'

services:
  app:
    build: .
    ports:
      - "3000:3000"
    command: bundle exec rails s -p 3000 -b '0.0.0.0'
    volumes:
      - .:/origin-001
      - bundle:/usr/local/bundle
    tty: true
    stdin_open: true
    links:
      - db
  
  db:
    image: mysql:5.6
    environment:
      MYSQL_ROOT_PASSWORD: password
      MYSQL_DATABASE: root
    volumes:
      - mysql-data:/var/lib/mysql
    ports:
      - "4306:3306"

volumes:
  mysql-data:
  bundle: